# 数据集路径设置
datasets-path: "/home/hdl/project/fgvr_test/datasets"

# 模型路径设置
# qwen2.5-vl-7b-path: "/home/Dataset/Models/Qwen/Qwen2.5-VL-7B-Instruct"
# blip2-flan-t5-xxl-path: "/home/Dataset/Models/Blip/blip2-flan-t5-xxl"
# clip-vit-base-patch32: "/home/Dataset/Models/Clip/clip-vit-base-patch32"
Qwen-path: "/home/Dataset/Models/Qwen"
Blip-path: "/home/Dataset/Models/Blip"
Clip-path: "/home/Dataset/Models/Clip"

# 暂时未启用
# llava路径

# 环境配置
conda_env: "finer_dynamic"              # conda环境名称

