### 配置数据集、模型路径、虚拟环境名称的文件
### 运行 bash config_datasets_models.sh 使之生效，软链接配置，以及修改scripts/config.yaml下配置的虚拟环境

# 数据集路径设置
datasets-path: "/home/hdl/datasets/finer"

# 模型路径设置
Qwen-path: "/home/hdl/model/Qwen" # NAS路径："/home/Dataset/Models/Qwen"
Blip-path: "/home/Dataset/Models/Blip" # NAS路径："/home/Dataset/Models/Blip"
Clip-path: "/home/hdl/model/Clip" # NAS路径："/home/Dataset/Models/Clip"
# qwen2.5-vl-7b-path: "/home/Dataset/Models/Qwen/Qwen2.5-VL-7B-Instruct"
# blip2-flan-t5-xxl-path: "/home/Dataset/Models/Blip/blip2-flan-t5-xxl"
# clip-vit-base-patch32: "/home/Dataset/Models/Clip/clip-vit-base-patch32"

# 暂时未启用
# llava路径

# 环境配置
conda_env: "finer_dynamic"              # conda环境名称

