### K-shot检索图像的处理逻辑
# 多图像直接取平均还是更精细化处理
k_shot_image_processing: "average_images"
# 选项： 
#    average       # 多图像直接取平均
#    fine_grained  # 更精细化处理

### 图-文 与 图-文 相似度的计算
# 粗糙图文拼接相似度还是加权后分开图文，分别加权计算相似度
image_text_similarity: "coarse_concat"
# 选项：
#    coarse_concat        # 粗糙图文拼接相似度
#    weighted_separate    # 加权后分开图文，分别加权计算相似度


### 其他待实现逻辑
### ...


