qwen2.5-vl-7b-path: "/home/Dataset/Models/Qwen/Qwen2.5-VL-7B-Instruct"
datasets-path: "/home/hdl/project/fgvr_test/datasets"

# 环境配置
environment:
  conda_env: "finer_dynamic"              # conda环境名称
  conda_base: "/home/hdl/miniconda3"      # conda安装路径
  project_root: "/home/hdl/project/fgvr_test"  # 项目根目录

