# EuroSAT 实验配置
setup: ours
experiment: 5.0

# Dataset
dataset_name: eurosat
num_classes: 10
num_base: 5
num_novel: 5

# Training
seed: 1
batch_size: 128  # 卫星图像较小，可以使用较大batch size

# Text-clustering Method
clustering_method: multi_clip_voting

# Model
model_size: ViT-B/16
model_size_vqa: OPT6.7B-COCO
model_size_mllm: Qwen2.5-VL-7B
model_type_llm: gpt-3.5-turbo

image_size: 224
verbose: False

