# Food-101 实验配置
setup: ours
experiment: 5.0

# Dataset
dataset_name: food
num_classes: 101
num_base: 50
num_novel: 51

# Training
seed: 1
batch_size: 96  # 食物图像复杂度中等

# Text-clustering Method
clustering_method: multi_clip_voting

# Model
model_size: ViT-B/16
model_size_vqa: OPT6.7B-COCO
model_size_mllm: Qwen2.5-VL-7B
model_type_llm: gpt-3.5-turbo

image_size: 224
verbose: False

